repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code with clippy
        entry: bash -c 'export PATH="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin:$PATH" && cargo clippy --all-targets -- -W clippy::all -D warnings'
        language: system
        types: [rust]
        pass_filenames: false
        require_serial: true

      - id: cargo-test
        name: cargo test
        description: Run tests
        entry: bash -c 'export PATH="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin:$PATH" && cargo test --all-targets'
        language: system
        types: [rust]
        pass_filenames: false
        require_serial: true
